# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b3f645d5cf32520ef5a068109e106c8669baa5a3ac843076f89dcf1db167a7a3d91c1956517dca2b2ac9159f8eec905426fb79e819767fb42da0f436b1ac8e4

test:
  secret_key_base: bd6c28be55abd02d77fdf2c793b05e1b43b65cf30df7e9f42f37ae3c68d7f9fdab82c159de19b7c5355493cd5945a4f41e9f2bd0b770e87111bb6a551820af6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
